# Minimizing overall test execution time by running campaign in optimal order

## Context

Considering a set of tests that have to be run on a given data sample; considering that on this given data sample, we have already computed the probability for each test to pass or fail; considering that once a test has passed, the campaign stops, meaning the other remaining tests do not need to be executed; Hence the problem:
**in which order should we execute the tests to minimize the overall test execution time?**

## Generating the data

In [1]:
import numpy as np
nb_tests = 3
data = np.array([ np.arange(nb_tests), np.random.rand(nb_tests), np.random.rand(nb_tests)*10 ])
print(data)

[[ 0.          1.          2.        ]
 [ 0.89459063  0.41318072  0.19150126]
 [ 5.01369347  7.35423989  2.50302183]]


In [2]:
p = data[1,:]
print(p)

[ 0.89459063  0.41318072  0.19150126]


In [3]:
t = data[2,:]
print(t)

[ 5.01369347  7.35423989  2.50302183]


In [4]:
cst = np.cumsum(t)
print(cst)

[  5.01369347  12.36793336  14.87095518]


In [5]:
cpp = np.cumprod(1-p)
print(cpp)

[ 0.10540937  0.06185625  0.0500107 ]


In [6]:
cpp[-1] = 0;
print(cpp)

[ 0.10540937  0.06185625  0.        ]


## Cost function
$J = \sum_{i=1}^n \left( p_i \cdot \prod_{k=0}^{i-1} \left(1-p_{k}\right) \cdot \sum_{j=1}^i t_j \right)$, with $p_0 = 0$.

In [7]:
cost = 0;
for i in range(0, nb_tests):
    cost += p[i] * cpp[i-1] * t[i]
print(cost)

0.349949757736


## Optimization problem
$\min \left( \sum_{i=1}^n \left( p_i \cdot \prod_{k=0}^{i-1} \left(1-p_{k}\right) \cdot \sum_{j=1}^i t_j \right) \right)$, with $p_0 = 0$.